apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-configmap
data:
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
  DB_NAME: "coworking"
  DB_USERNAME: "coworkinguser"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret
type: Opaque
data:
  DB_PASSWORD: Y293b3JraW5ncGFzczEyMw==
